import { CrystalCategory, type CrystalDefinition, type FusionRecipe } from '../types/crystal.js';

export const CRYSTAL_DEFINITIONS: Record<CrystalCategory, CrystalDefinition> = {
  [CrystalCategory.Fire]: {
    id: 'crystal_fire',
    category: CrystalCategory.Fire,
    displayName: 'Fire Crystal',
    primaryColor: '#FF4500',
    secondaryColor: '#FFD700',
    emissiveIntensity: 1.4,
    shape: 'tetrahedron',
    abilityId: 'phoenix_rebirth',
  },
  [CrystalCategory.Ice]: {
    id: 'crystal_ice',
    category: CrystalCategory.Ice,
    displayName: 'Ice Crystal',
    primaryColor: '#00BFFF',
    secondaryColor: '#E0FFFF',
    emissiveIntensity: 1.0,
    shape: 'octahedron',
    abilityId: 'frost_freeze',
  },
  [CrystalCategory.Nature]: {
    id: 'crystal_nature',
    category: CrystalCategory.Nature,
    displayName: 'Nature Crystal',
    primaryColor: '#32CD32',
    secondaryColor: '#90EE90',
    emissiveIntensity: 0.9,
    shape: 'icosahedron',
    abilityId: 'growth_bloom',
  },
  [CrystalCategory.Storm]: {
    id: 'crystal_storm',
    category: CrystalCategory.Storm,
    displayName: 'Storm Crystal',
    primaryColor: '#7B68EE',
    secondaryColor: '#E6E6FA',
    emissiveIntensity: 1.3,
    shape: 'prism',
    abilityId: 'lightning_chain',
  },
  [CrystalCategory.Void]: {
    id: 'crystal_void',
    category: CrystalCategory.Void,
    displayName: 'Void Crystal',
    primaryColor: '#4B0082',
    secondaryColor: '#9400D3',
    emissiveIntensity: 1.1,
    shape: 'dodecahedron',
    abilityId: 'void_consume',
  },
  [CrystalCategory.Plasma]: {
    id: 'crystal_plasma',
    category: CrystalCategory.Plasma,
    displayName: 'Plasma Crystal',
    primaryColor: '#FF00FF',
    secondaryColor: '#FF69B4',
    emissiveIntensity: 1.5,
    shape: 'octahedron',
    abilityId: 'plasma_burst',
  },
  [CrystalCategory.Celestial]: {
    id: 'crystal_celestial',
    category: CrystalCategory.Celestial,
    displayName: 'Celestial Crystal',
    primaryColor: '#FFD700',
    secondaryColor: '#FFFACD',
    emissiveIntensity: 1.2,
    shape: 'icosahedron',
    abilityId: 'starfall',
  },
  [CrystalCategory.Quantum]: {
    id: 'crystal_quantum',
    category: CrystalCategory.Quantum,
    displayName: 'Quantum Crystal',
    primaryColor: '#00CED1',
    secondaryColor: '#7FFFD4',
    emissiveIntensity: 1.3,
    shape: 'dodecahedron',
    abilityId: 'time_rewind',
  },
  [CrystalCategory.Cosmic]: {
    id: 'crystal_cosmic',
    category: CrystalCategory.Cosmic,
    displayName: 'Cosmic Crystal',
    primaryColor: '#1E90FF',
    secondaryColor: '#87CEEB',
    emissiveIntensity: 1.1,
    shape: 'prism',
    abilityId: 'cosmic_shift',
  },
  [CrystalCategory.Shadow]: {
    id: 'crystal_shadow',
    category: CrystalCategory.Shadow,
    displayName: 'Shadow Crystal',
    primaryColor: '#2F2F4F',
    secondaryColor: '#696969',
    emissiveIntensity: 0.8,
    shape: 'tetrahedron',
    abilityId: 'shadow_clone',
  },
  [CrystalCategory.Dragon]: {
    id: 'crystal_dragon',
    category: CrystalCategory.Dragon,
    displayName: 'Dragon Crystal',
    primaryColor: '#DC143C',
    secondaryColor: '#FF6347',
    emissiveIntensity: 1.6,
    shape: 'dodecahedron',
    abilityId: 'dragon_breath',
  },
  [CrystalCategory.Ancient]: {
    id: 'crystal_ancient',
    category: CrystalCategory.Ancient,
    displayName: 'Ancient Crystal',
    primaryColor: '#DAA520',
    secondaryColor: '#F0E68C',
    emissiveIntensity: 1.4,
    shape: 'icosahedron',
    abilityId: 'ancient_awakening',
  },
};

export const FUSION_RECIPES: FusionRecipe[] = [
  {
    inputs: [CrystalCategory.Fire, CrystalCategory.Storm],
    result: CrystalCategory.Plasma,
    resultName: 'Thunder Crystal',
    exclusiveAbility: 'thunder_strike',
  },
  {
    inputs: [CrystalCategory.Nature, CrystalCategory.Ice],
    result: CrystalCategory.Celestial,
    resultName: 'Frost Bloom Crystal',
    exclusiveAbility: 'frost_bloom',
  },
  {
    inputs: [CrystalCategory.Quantum, CrystalCategory.Void],
    result: CrystalCategory.Cosmic,
    resultName: 'Singularity Crystal',
    exclusiveAbility: 'singularity_collapse',
  },
  {
    inputs: [CrystalCategory.Dragon, CrystalCategory.Celestial],
    result: CrystalCategory.Ancient,
    resultName: 'Star Dragon Crystal',
    exclusiveAbility: 'star_dragon_fury',
  },
];

export const MATCHABLE_CATEGORIES = [
  CrystalCategory.Fire,
  CrystalCategory.Ice,
  CrystalCategory.Nature,
  CrystalCategory.Storm,
  CrystalCategory.Void,
  CrystalCategory.Plasma,
] as const;
